### ISSUE TITLE
Documentation for response error handling outdated?

### ISSUE THREAD

**Issue by bs-thomas** [forwardemail/superagent#1044]
According to the docs, when there is an error (eg. 404), I have to obtain the error using "err.status".
http://visionmedia.github.io/superagent/#error-handling

```
if (err && err.status === 404) {
  alert('oh no ' + res.body.message);
}
```

However, when I tried to make a 404 error, "err" only shows a text-based message, doesn't seem like an object.

Here is what I get from console.log()

```
Error: Not Found
    at Request.<anonymous> (http://localhost/codebase/assets/portal/js/vendor.js:76987:19)
    at Request.Emitter.emit (http://localhost/codebase/assets/portal/js/vendor.js:5623:20)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost/codebase/assets/portal/js/vendor.js:77258:10)
```

I know I can get that status information in "res", but the above is not the purpose my current task.  It is though a factor I must consider before I decide on my approach.  I would like to understand how it functions completely (including border line cases) before I start writing my code.  I found that it doesn't quite work like the documentation suggests.
# 

This also doesn't work as documented I think.  The 404 error doesn't seem to come into here, though it does trigger "end()" callback method:

```
                    .on('error', function(err) {
                        console.log('Error: ', res, err);
                    })
```
# 

May I ask if the doc is outdated or something?  Or if I completely misunderstood, please do let me know.

Your help is appreciated.  Thanks!

Cheers,
Thomas

**Comment by pornel** [comment]
You `console.log` looks correct, as if it printed an `Error` object, not a string, so `err.status` should still be possible.

Note that `err.status` is available only if the server responded. If server didn't respond (e.g. client is offline, or server is down), then there will be no HTTP status to report.

**Comment by bs-thomas** [comment]
@pornel Wow that was some quick response.  Thank you so much!!

Hope you don't mind me asking one more question.  If there is network connection errors such as timeout, how should I detect that then?

Thanks again!

**Comment by pornel** [comment]
Existence of `err` should be enough. The browser does not report why connection failed (we only get `status = 0`).

**Comment by bs-thomas** [comment]
@pornel Understood.  So may I confirm there is currently no way of knowing the callback is triggered by timeout / abort?

The reason why I'm asking is because it would be great to know what type of error was called back, for logging purposes.

I noticed that jQuery's $.ajax actually has some non-response related errors:
"error", "timeout", "abort", or "parsererror"
[http://api.jquery.com/jquery.ajax/](http://api.jquery.com/jquery.ajax/)

The first 3 errors are related to network connection I believe, and the 4th one is a parseerror.

Thanks!

**Comment by pornel** [comment]
In case of a timeout the error has `.timeout` property.

**Comment by titanism** [comment]
The response error handling documentation has been updated. Closing this out.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
