### ISSUE TITLE
Error with BOM

### ISSUE THREAD

**Issue by rosyaniv** [forwardemail/superagent#1249]
When making a POST request from the server and getting a JSON with BOM (first character is '0xFEFF'), the response leads to an error.
There's a way of handling this, by using .parse(fn) where this function is parsing and strips the BOM character, but isn't there a better way of doing this?

(BTW, I just moved to 3.5.2 where this issue began. In version 1.2.0 it was working without any problems)

Thanks

**Comment by pornel** [comment]
Can you specify what error do you get exactly? Can you provide a test case?

**Comment by rosyaniv** [comment]
Sure.
I'm making a request to a WCF Web Service.
This is the error I get. The empty character after the word "token" is what causing all this - 0xFEFF (I replaced some specific project names and data with '...'):

`{ SyntaxError: Unexpected token ﻿ in JSON at position 0
    at Object.parse (native)
    at Stream.<anonymous> (/home/.../node_modules/superagent/lib/node/parsers/json.js:8:35)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (/home/.../node_modules/superagent/lib/node/unzip.js:53:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  rawResponse: '﻿{"Successful":true,...
  statusCode: 200,
  response: undefined }`

**Comment by pornel** [comment]
Hmm, UTF-8 BOM is 0xEF,0xBB,0xBF. If you're getting 0xFEFF that's a big endian UTF-16. It's an [awful encoding](https://softwareengineering.stackexchange.com/questions/102205/should-utf-16-be-considered-harmful) that [has no good reason to be used](http://utf8everywhere.org/), so it would be best if you could ask server operator to use UTF-8 instead.

I'm surprised that UTF-16 has ever worked with superagent. Node generally defaults to interpreting all text-like streams as UTF-8.

**Comment by titanism** [comment]
Thanks for reporting this. It is fixed in v10.4.0.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
