### ISSUE TITLE
 Error: Unauthorized

### ISSUE THREAD

**Issue by PierreGriffith** [forwardemail/superagent#1312]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 Error: Unauthorized
 at Request.callback (/var/meep2/Expertsa/V2-Serveur-OLD/node_modules/superagent/lib/node/index.js:699:13)
 at parser (/var/meep2/Expertsa/V2-Serveur-OLD/node_modules/superagent/lib/node/index.js:903:18)
 at IncomingMessage.res.on (/var/meep2/Expertsa/V2-Serveur-OLD/node_modules/superagent/lib/node/parsers/json.js:19:7)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1056:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)

i'm actually having this error only on my vps. " Error: Unauthorized", what should id do for make it possible ?

**Comment by pornel** [comment]
1. You're using superagent as a promise (`request.then()` or `await request`)
2. You're not handling all errors. In Node.js you have to call a `.catch()` (or `then()` with 2nd arg, or `await`) on *every single promise* created.

**Comment by titanism** [comment]
HTTP 401 is represented as an error. Handle Promise rejection with catch/try-catch; no library defect is shown.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
