### ISSUE TITLE
stream.pipe(request) Error: socket hang up

### ISSUE THREAD

**Issue by zfcheng** [forwardemail/superagent#1317]
Hi:
  I have a problem，
  code:
```
var stream = fs.createWriteStream(path.join(__dirname, './test.json'));
request = new Request(method, url);
stream.pipe(request);
```
Upload about 100 K file no problem
But there will be a mistake in more than 200 K

Error is 
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketCloseListener (_http_client.js:286:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12) code: 'ECONNRESET', response: undefined }
```
After the examination, no problems were found, can you help me?

**Comment by pornel** [comment]
Can you verify it happens with other servers? It looks like a connection closed by the server, so the problem may be servers-side, and not in superagent.

**Comment by zfcmt** [comment]
Thank you very much for your answer.
I check on the server, the server did not receive the next data of the client, Content-length and the received content of the length does not match, the server waiting for timeout to actively disconnect the link, and then the client throws an exception.

I try to set highWaterMark larger than sending files, and like this, requests are successful
```
let stream = fs.createReadStream(file, {
    highWaterMark: 300000
})
request = new Request(method, url);
stream.pipe(request);
```
The server should not receive the complete stream, if I do not set highWaterMark, but use default values, can solve this problem?
Do you have any ideas about this question?

**Comment by pornel** [comment]
Your server may not be expecting to receive unstructured POST. Try using `request.post().attach('file', stream)` instead.

**Comment by zfcmt** [comment]
But my interface is PUT. Is there any other way?

**Comment by pornel** [comment]
If it's put then it should work. Are you setting content-length?

**Comment by zfcmt** [comment]
yes, I set up Content-Length, and it was right, but I didn't know why stream was interrupted.

**Comment by zfcmt** [comment]
When I upload stream, I use require ('http').Request, and the upload is successful. I think what SuperAgent did when uploading stream, see the code has nothing to find, and I will continue to follow this problem.

code:
```
var http = require('http');

function stream (req, callback) {
    var options = {
        host: req.headers.Host,
        port: req.port,
        method: req.method,
        headers: req.headers,
        path: req.path
    }
    return http.request(options, function (httpResp) {
        callback(httpResp);
        httpResp.emit('headers', httpResp.statusCode, httpResp.headers);
    });
}
module.exports = stream;
```
```
readStream.pipe(stream);
```

**Comment by jon-cooke-rentalcars** [comment]
I had the same issue, solved in the same way - using http.request instead. I'm using node 10.6.0

**Comment by gramakri** [comment]
I think https://github.com/visionmedia/superagent/issues/1654 might be the root cause

**Comment by titanism** [comment]
This is the repeated-drain/backpressure issue tracked by #1654. Current one-shot drain remains unfixed; use #1654 for the patch and regression test.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
