### ISSUE TITLE
how to detach/unset cookies for superagent agent 

### ISSUE THREAD

**Issue by JadyNews** [forwardemail/superagent#1348]
We use superagent to get SAML integration with AWS, when posting request to the SAML IdP (Okta) we have to use agent to include cookies in order to get the SAML metadata back, but the cookies needs to detach/unset when making request to AWS to assume role.

Is that a way to implement it?

Thank you in advanced,
Jady

**Comment by kornelski** [comment]
By default all cookies are thrown away.

Cookies are preserved only by a copy of an agent (`.agent()`) so create and use a copy of an agent for as long as you need its cookies.

**Comment by JadyNews** [comment]
@kornelski , thanks. What about session ID? Is there a way to re-initial it?
User1 logs in, superagent get SAML assertion from IdP(Okta), user1 uses this metadata to log in to AWS, but when user2 logs in, superagent is able to get another SAML assertion, it fails when calling AWS with this SAML metadata as I found the session ID is the same when calling from AWS sdk.

I got error message. 
{ 
InvalidIdentityToken: SAML Assertion doesn't contain the requested Role and Metadata in the attributes
    at Request.extractError (/Users/sentry/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/Users/sentry/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/sentry/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/sentry/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/sentry/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/sentry/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/sentry/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/sentry/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/sentry/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/sentry/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/sentry/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/sentry/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/sentry/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/sentry/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/sentry/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/sentry/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'SAML Assertion doesn\'t contain the requested Role and Metadata in the attributes',
  code: 'InvalidIdentityToken',
  requestId: '7ccd975a-1690-11e8-91fd-251c48d5b45c',
  statusCode: 400,
  retryable: false,
  retryDelay: 75.63778962412593 }

I would really appreciate it if anyone could help with this issue, or give me any recommendations.

Thank you in advanced,
Jady

**Comment by JadyNews** [comment]
@kornelski , I am new here, could you please confirm that if I use superagent.agent(). After .end() will the session be closed. 

For example, user1 uses superagent.agent() to call an API to get response SAML back and do something, after it, user2 uses superagent.agent() to call same API. Will the user1's session still preserved when user2 making the call ?

The code snippet is below:

var request = require('superagent');
var agent = request.agent();
agent
    .get(`${config.oktaAppURL}`)
    .query({ sessionToken: sessionToken })
    .set('Accept',  '*/*')
    .end(function(err, res) {
      if (err) {
        logger.error('Call okta app url to get SAML assertion: ' +
        'can\'t not query to this app url');
        callback(err);
      }
      else {
        // do something
          return callback(null, data);
        }
        else {
          // do something
          return callback(err);
        }
      }
    });

**Comment by kornelski** [comment]
Each instance of an agent has separate cookies. If you make two agents, they will be like two users.

**Comment by titanism** [comment]
.end() does not clear cookies. Use one superagent.agent() per user/session or create a fresh agent to start without prior cookies; do not share agents across users.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.

**Comment by titanism** [comment]
Closing this for now. If this still affects v10.4.0, please open a new issue with a current reproduction.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
