### ISSUE TITLE
Missing async trace in Node V12

### ISSUE THREAD

**Issue by tsingyee** [forwardemail/superagent#1484]
Node V12 supports full async stack trace, but superagent error stack still missing the outter async stack trace when there is error thrown from super agent, e.g a server 500 internal error.
Is there anything need to be fixed from superagent side to keep the async stack trace?

    at Response.toError (C:\dev\LT\wise-report-center\node_modules\superagent\lib\node\response.js:98:13)
    at ResponseBase._setStatusProperties (C:\dev\LT\wise-report-center\node_modules\superagent\lib\response-base.js:119:48)
    at new Response (C:\dev\LT\wise-report-center\node_modules\superagent\lib\node\response.js:44:8)
    at Request._emitResponse (C:\dev\LT\wise-report-center\node_modules\superagent\lib\node\index.js:909:18)
    at C:\dev\LT\wise-report-center\node_modules\superagent\lib\node\index.js:1105:42
    at IncomingMessage.<anonymous> (C:\dev\LT\wise-report-center\node_modules\superagent\lib\node\parsers\json.js:22:7)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)

**Comment by tsingyee** [comment]
I have a work around for now, manually keep the async stack trace before call superagent, and add it back if necessary.

let httpClient = {};
['get', 'post', 'delete', 'put'].forEach((method) => {
    let methodFn = superagent[method];
    httpClient[method] = async function (requestUrl, data, fn) {
        let responsePromise = methodFn.call(null, requestUrl, data, fn).ca(caCerts);

        let originalStack;
        try {
            throw new Error("\noriginal stack trace");
        } catch (e) {
            originalStack = e.stack;
        }

        try {
            let response = await responsePromise;
            return response.body;
        } catch (e) {
            e.originalStack = e.stack + originalStack;
            throw e;
        }

    };
});

**Comment by rektide** [comment]
Does anyone have any workarounds for this? This is one of the most persistent & frustrating things my team experiences. We see this on Node v14.19.1 too.

**Comment by titanism** [comment]
HTTP error stack begins at Response.toError rather than request creation. A design must define capture timing, composition, callback/promise support and Node-version tests.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.

**Comment by titanism** [comment]
Closing this for now. If this still affects v10.4.0, please open a new issue with a current reproduction.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
