### ISSUE TITLE
Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by ygtzz** [forwardemail/superagent#1592]
while I request a file from a server in koa
```javascript
router.post('/proxy', async function (ctx) {
    let postParam = ctx.request.body;
    let fileName = urlencode.decode(postParam.fileName);
    let filePath = urlencode.decode(postParam.filePath);
    filePaths = filePath.split('/');
    filePaths = filePaths.slice(0,-1);
    filePath = filePaths.join('/') + '/' + postParam.fileName;
    console.log('filePath: ', filePath)

    let res = superagent.get(postParam.filePath);
    let passThroughtStream = new stream.PassThrough();
    res.pipe(passThroughtStream);

    ctx.set("Content-disposition", "attachment; filename=" + postParam.fileName);
    ctx.type = filePath.split('.')[1];
    ctx.body = passThroughtStream;
});
```
superagent makes error:
```javascript
TypeError: Cannot read property 'request' of undefined
      at Request.request (/Users/mengff/Documents/workspace/github/download-demo/node_modules/_superagent@6.1.0@superagent/lib/node/index.js:795:18)
      at Request.end (/Users/mengff/Documents/workspace/github/download-demo/node_modules/_superagent@6.1.0@superagent/lib/node/index.js:951:8)
      at Request.pipe (/Users/mengff/Documents/workspace/github/download-demo/node_modules/_superagent@6.1.0@superagent/lib/node/index.js:434:8)
      at /Users/mengff/Documents/workspace/github/download-demo/index.js:66:9
      at dispatch (/Users/mengff/Documents/workspace/github/download-demo/node_modules/_koa-compose@4.1.0@koa-compose/index.js:42:32)
      at /Users/mengff/Documents/workspace/github/download-demo/node_modules/_koa-router@9.4.0@koa-router/lib/router.js:372:16
      at dispatch (/Users/mengff/Documents/workspace/github/download-demo/node_modules/_koa-compose@4.1.0@koa-compose/index.js:42:32)
      at /Users/mengff/Documents/workspace/github/download-demo/node_modules/_koa-compose@4.1.0@koa-compose/index.js:34:12
      at dispatch (/Users/mengff/Documents/workspace/github/download-demo/node_modules/_koa-router@9.4.0@koa-router/lib/router.js:377:31)
      at dispatch (/Users/mengff/Documents/workspace/github/download-demo/node_modules/_koa-compose@4.1.0@koa-compose/index.js:42:32)
```

**Comment by titanism** [comment]
Provide standalone code, exact versions, redacted filePath and URL/protocol. Confirm a simple absolute URL pipe reproduces before changing code.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.

**Comment by titanism** [comment]
Closing this for now. If this still affects v10.4.0, please open a new issue with a current reproduction.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
