### ISSUE TITLE
post set content-length error

### ISSUE THREAD

**Issue by sherryhhx** [forwardemail/superagent#1730]

**Comment by sherryhhx** [comment]
The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. 
Received an instance of Object at Function.byteLength (buffer.js:724:11)
at Request._end (xxxx/node_modules/superagent/lib/node/index.js:804:84) 
at Request.end (xxx/node_modules/superagent/lib/node/index.js:777:15)

**Comment by Woodz** [comment]
To clarify this bug, this happens when trying to call `.send` with an object, e.g.
```
await request(app.getHttpServer())
            .post('/foo/bar')
            .send({a: 1});
```

The workaround is to call JSON.stringify on the payload, e.g.
```
await request(app.getHttpServer())
            .post('/foo/bar')
            .send(JSON.stringify({a: 1}));
```

Superagent should catch this by tightening TS typing and should have a nicer error message

**Comment by titanism** [comment]
Object .send() now serializes as JSON before Content-Length calculation. The reported Buffer.byteLength(Object) failure appears older; reopen with current repro.

v10.4.0 is available on npm: https://www.npmjs.com/package/superagent/v/10.4.0
GitHub release: https://github.com/forwardemail/superagent/releases/tag/v10.4.0

Consider supporting our efforts to maintain this project by using Forward Email at https://forwardemail.net.  We run the only 100% open source and 3rd party audited email service in the world.
